[package]
name = "volt-core"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.4"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.149"
rayon = "1.11.0"
tree-sitter = "0.26.5"
tree-sitter-rust = "0.23.3"
tree-sitter-java = "0.23.5"
tree-sitter-go = "0.25.0"
